/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto.forms.old;

/**
 *
 * @author Catalin Glavan
 */
public class first extends javax.swing.JFrame implements helper {

    public first() {
        initComponents();
        super.setBackground(new java.awt.Color(0, 255, 0, 0));
        super.setLocationRelativeTo(null);
        form_listener moveForm = new form_listener(this);
        super.addMouseListener(moveForm);
        super.addMouseMotionListener(moveForm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panel_left = new javax.swing.JPanel();
        intro = new crypto.forms.old.intro(this);
        panel_right = new javax.swing.JPanel();
        login = new crypto.forms.old.login(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(0, 255, 0, 0));
        bg.setLayout(new java.awt.BorderLayout());

        panel_left.setBackground(new java.awt.Color(0, 255, 0, 0));

        javax.swing.GroupLayout panel_leftLayout = new javax.swing.GroupLayout(panel_left);
        panel_left.setLayout(panel_leftLayout);
        panel_leftLayout.setHorizontalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addComponent(intro, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_leftLayout.setVerticalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addComponent(intro, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(panel_left, java.awt.BorderLayout.CENTER);

        panel_right.setVisible(false);
        panel_right.setBackground(new java.awt.Color(0, 255, 0, 0));

        javax.swing.GroupLayout panel_rightLayout = new javax.swing.GroupLayout(panel_right);
        panel_right.setLayout(panel_rightLayout);
        panel_rightLayout.setHorizontalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rightLayout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_rightLayout.setVerticalGroup(
            panel_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        bg.add(panel_right, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private crypto.forms.old.intro intro;
    private crypto.forms.old.login login;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_right;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refreshFrame() {
        super.invalidate();
        super.validate();
        super.repaint();
    }

    @Override
    public void intro() {
        panel_right.setVisible(false);
        panel_left.setVisible(true);
        super.setLocation(super.getX() + 260, super.getY());
        refreshFrame();
        super.pack();
    }

    @Override
    public void step1() {
        panel_left.setVisible(false);
        refreshFrame();
        super.pack();
        super.setLocation(super.getX() - 260, super.getY());
        panel_right.setVisible(true);
        refreshFrame();
        super.pack();
    }

    @Override
    public void step2() {
    }

    @Override
    public void state_minimize() {
        super.setState(javax.swing.JFrame.ICONIFIED);
    }

    @Override
    public void state_normal() {
        super.setState(javax.swing.JFrame.NORMAL);
    }
}
