/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto.simple_forms;

import crypto.helper.configApp;
import crypto.sql.DBConnect;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;

import javax.swing.*;
import java.awt.*;
import java.text.ParseException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Catalin Glavan
 */
public class intro extends javax.swing.JFrame {

    public intro(Point location, String helper) {
        checkLanguage(helper);
        initComponents();
        super.setIconImage(new ImageIcon(getClass().getResource(config.getIconPath())).getImage());

        checkLangButtons();
        checkLocation(location);
        closeWindow();
        DBConnect sql = new DBConnect();
        sql.DBConnectSQL(config.getUsername(), config.getPassword(), config.getDatabase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intro_bg = new crypto.helper.intro_bg();
        next = new javax.swing.JButton();
        lang = new javax.swing.JLabel();
        en = new javax.swing.JButton();
        ro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(bundle.getString("key_intro_title")
        );
        setResizable(false);

        intro_bg.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                intro_bgAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        next.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        next.setText(bundle.getString("key_next"));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        lang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lang.setText(bundle.getString("key_lang"));

        en.setSelected(lang_helper);
        en.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crypto/images/simple_forms/en.png"))); // NOI18N
        en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enActionPerformed(evt);
            }
        });

        ro.setSelected(!lang_helper);
        ro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crypto/images/simple_forms/ro.png"))); // NOI18N
        ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout intro_bgLayout = new javax.swing.GroupLayout(intro_bg);
        intro_bg.setLayout(intro_bgLayout);
        intro_bgLayout.setHorizontalGroup(
            intro_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intro_bgLayout.createSequentialGroup()
                .addGroup(intro_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(intro_bgLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(intro_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(intro_bgLayout.createSequentialGroup()
                                .addComponent(en)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ro))
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(intro_bgLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lang)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        intro_bgLayout.setVerticalGroup(
            intro_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, intro_bgLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(lang)
                .addGap(18, 18, 18)
                .addGroup(intro_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(en, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(114, 114, 114)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intro_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intro_bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (evt.getSource() == next) {
            new login(setPoint, bundle).setVisible(true);
            super.dispose();
        }
    }//GEN-LAST:event_nextActionPerformed

    private void enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enActionPerformed
        if (evt.getSource() == en) {
            refreshFrame("en");
        }
    }//GEN-LAST:event_enActionPerformed

    private void roActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roActionPerformed
        if (evt.getSource() == ro) {
            refreshFrame("ro");
        }
    }//GEN-LAST:event_roActionPerformed

    private void intro_bgAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_intro_bgAncestorMoved
        setPoint = super.getLocation();
    }//GEN-LAST:event_intro_bgAncestorMoved

    private void closeWindow() {

        super.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                ImageIcon icon = new ImageIcon(getClass().getResource(config.getIconPath()));
                if (JOptionPane.showConfirmDialog(
                        windowEvent.getWindow(),
                        bundle.getString("key_msg_close"), bundle.getString("key_msg_close_title"),
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        icon
                ) == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
    }

    private void checkLocation(Point location) {
        setPoint = location;
        if (setPoint == null) {
            super.setLocationRelativeTo(null);
        } else {
            super.setLocation(setPoint);
        }
    }

    private void checkLangButtons() {
        if (en.isSelected()) {
            en.requestFocus();
        } else {
            ro.requestFocus();
        }
    }

    private void checkLanguage(String helper) {
        try {
            switch (helper) {
                case "en":
                    lang_helper = true;
                    break;
                case "ro":
                    lang_helper = false;
                    break;
            }
        } catch (NullPointerException e) {
            lang_helper = config.getLang().equals("en");
        }
        final Locale RO = new Locale("ro", "Romania");
        final Locale EN = new Locale("en", "US");
        bundle = lang_helper ? ResourceBundle.getBundle("crypto/helper/lang_en", EN) : ResourceBundle.getBundle("crypto/helper/lang_ro", RO);
    }

    private void refreshFrame(String helper) {
        intro.super.dispose();
        new intro(setPoint, helper).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new intro(setPoint, null).setVisible(true);
                }
            });
        } catch (ParseException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(intro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private static Point setPoint = null;
    private final configApp config = new configApp();
    private boolean lang_helper;
    private ResourceBundle bundle;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton en;
    private crypto.helper.intro_bg intro_bg;
    private javax.swing.JLabel lang;
    private javax.swing.JButton next;
    private javax.swing.JButton ro;
    // End of variables declaration//GEN-END:variables
}
